# fortytwode — common dev tasks. Run `make <target>` (defaults to `build`).
#
# A .env in this directory is loaded automatically and its vars exported to the
# run targets (so DATABASE_URL, FT_CLIENT_ID, etc. reach the binary). Use the
# .env.example format: plain KEY=value, no quotes. Exporting in your shell still
# works too.
ifneq (,$(wildcard .env))
include .env
export
endif

BINARY := fortytwode

# build: regenerate templ code, then compile the binary (default target)
build: generate
	go build -o $(BINARY) .

# generate: regenerate the templ view code (internal/view/*_templ.go)
generate:
	go generate ./...

# dev: build + run the full stack (db, app, HTTP Nginx) at http://localhost:8080,
# rebuilding the app on source edits via `docker compose watch`
dev:
	docker compose up --build --watch

# prod: (re)start the production stack (TLS + rate-limiting Nginx) on :80/:443,
# detached. Assumes a cert already exists — use `make deploy` for the first run.
prod:
	docker compose -f docker-compose.yml -f deploy/docker-compose.prod.yml up --build -d

# cert: obtain/renew the Let's Encrypt certificate. Usually run via `make deploy`;
# use standalone only when you need to renew the cert without redeploying prod.
cert:
	docker compose -f deploy/docker-compose.cert.yml up --force-recreate --exit-code-from certbot
	docker compose -f deploy/docker-compose.cert.yml down

# deploy: full prod deploy/renewal - `down` -> `cert` -> `prod`
deploy: down cert prod

# migrate: apply any pending database migrations against the running stack's db.
# serve also applies them on boot; this runs them standalone (e.g. before a deploy)
# without starting the server. --build picks up the current source.
migrate:
	docker compose run --build --rm app migrate

# backup: dump the database to ./backup-<timestamp>.dump (Postgres custom format).
# Restore with:
#   docker compose exec -T db pg_restore -U fortytwode -d fortytwode --clean < <file>
backup:
	docker compose exec -T db pg_dump -U fortytwode -Fc fortytwode > backup-$$(date +%F-%H%M).dump

# schema: regenerate the reference internal/store/schema.sql from the running db.
# Reference only — the source of truth is internal/store/migrations/*.sql.
schema:
	@echo "Regenerating schema..."
	@bash -o pipefail -c '{ echo "-- REFERENCE ONLY — generated by '\''make schema'\'', NOT executed. The source"; \
	  echo "-- of truth is internal/store/migrations/*.sql, applied by store.Migrate."; \
	  echo; \
	  docker compose exec -T db pg_dump --schema-only --no-owner -U fortytwode fortytwode 2>/dev/null; } \
	  | docker run --rm -i -v "$$(pwd):/src" -w /src golang:1.26-alpine go run ./internal/store/schema_prettify 2>/dev/null \
	  > internal/store/schema.sql' \
	  && echo "Schema written to internal/store/schema.sql" \
	  || { echo "Failed to regenerate schema" >&2; exit 1; }

# pull: fetch latest changes from the remote
pull:
	git pull

# update-prod: pull, migrate, and relaunch prod
update-prod: pull migrate prod

# down: stop and remove the stack's containers
down:
	docker compose down

# volume-rm: remove the data volume (run after `make down` to ensure containers are stopped)
volume-rm:
	docker volume rm fortytwode_pgdata

# prune: remove all containers and locally-built images for this project's compose
prune:
	docker compose down --rmi local

# logs: follow the stack's logs
logs:
	docker compose logs -f

# fetch: build, then download your own 42 data into ./output (CLI personal tool)
fetch: build
	./$(BINARY) fetch

# fetch-curated: build, then dump only the single curated JSON we'd persist (./output/curated.json).
# Serves as a transparency preview of what the database stores
fetch-curated: build
	./$(BINARY) fetch curated

# fmt: format Go and templ source
fmt:
	gofmt -w .
	go tool templ fmt .

# fmt-check: fail if any Go file is not gofmt-clean (used by `check`/CI). Runs
# gofmt -w first to auto-fix, then -l to fail on anything that remained dirty
# (e.g. a file that couldn't be parsed).
fmt-check: fmt
	@out="$$(gofmt -l .)"; if [ -n "$$out" ]; then echo "gofmt needs running on:"; echo "$$out"; exit 1; fi

# vet: report suspicious constructs
vet: generate
	go vet ./...

# vuln: scan dependencies and reachable code for known CVEs
vuln:
	go tool govulncheck ./...

# check: format, vet, scan for known CVEs, and build
check: fmt-check vet vuln build

# tidy: prune go.mod / go.sum
tidy:
	go mod tidy

# clean: remove the binary and generated templ code
clean:
	rm -f $(BINARY)
	find internal -name '*_templ.go' -delete

# test: run the Go test suite
test:
	go test ./...

# setup-hooks: install the pre-push hook into .git/hooks/
setup-hooks:
	cp pre-push .git/hooks/pre-push
	chmod +x .git/hooks/pre-push

.PHONY: build generate dev prod cert deploy pull reload-prod migrate backup schema down volume-rm prune logs fetch fetch-curated fmt fmt-check vet vuln check tidy clean test setup-hooks
