#!/bin/sh

RED="\033[91m"
GREEN="\033[92m"
CYAN="\033[96m"
RESET="\033[0m"

echo $CYAN "Running pre-push checks..." $RESET

echo $CYAN "Running make check..." $RESET
make check
CHECK_EXIT=$?

echo $CYAN "Running make test..." $RESET
make test
TEST_EXIT=$?

if [ $CHECK_EXIT -ne 0 ] || [ $TEST_EXIT -ne 0 ]; then
  echo $RED "Pre-push checks failed. Push aborted. (bypass with 'git push --no-verify')" $RESET
  exit 1
fi

echo $GREEN "All checks passed." $RESET
exit 0
