-- REFERENCE ONLY — generated by 'make schema', NOT executed. The source
-- of truth is internal/store/migrations/*.sql, applied by store.Migrate.
CREATE TABLE accounts (
    id SERIAL PRIMARY KEY,
    email text NOT NULL UNIQUE,
    ft_id bigint NOT NULL UNIQUE,
    ft_login text NOT NULL UNIQUE,
    data jsonb NOT NULL,
    fetched_at timestamp with time zone NOT NULL,
    is_public boolean DEFAULT false NOT NULL,
    visibility jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    email_verified boolean DEFAULT false NOT NULL,
    verify_token_hash text,
    verify_sent_at timestamp with time zone,
    delete_token_hash text,
    delete_requested_at timestamp with time zone,
    login_token_hash text,
    login_sent_at timestamp with time zone,
    pending_email text,
    email_change_token_hash text,
    email_change_sent_at timestamp with time zone,
    preferred_theme text,
    CONSTRAINT accounts_preferred_theme_check CHECK ((preferred_theme = ANY (ARRAY['light'::text, 'dark'::text])))
);

CREATE TABLE schema_migrations (
    version integer PRIMARY KEY,
    name text NOT NULL,
    body text NOT NULL,
    applied_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE sessions (
    id text PRIMARY KEY,
    account_id bigint NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    expires_at timestamp with time zone NOT NULL
);

CREATE TABLE stats (
    id integer DEFAULT 1 PRIMARY KEY,
    downloads bigint DEFAULT 0 NOT NULL,
    profiles bigint DEFAULT 0 NOT NULL
);

CREATE TABLE sync_cooldowns (
    ft_id bigint PRIMARY KEY,
    last_sync_at timestamp with time zone NOT NULL
);

CREATE INDEX accounts_delete_token_hash_idx ON accounts (delete_token_hash) WHERE (delete_token_hash IS NOT NULL);

CREATE INDEX accounts_email_change_token_hash_idx ON accounts (email_change_token_hash) WHERE (email_change_token_hash IS NOT NULL);

CREATE INDEX accounts_login_token_hash_idx ON accounts (login_token_hash) WHERE (login_token_hash IS NOT NULL);

CREATE INDEX accounts_verify_token_hash_idx ON accounts (verify_token_hash) WHERE (verify_token_hash IS NOT NULL);
